### ISSUE TITLE
Switch to travis

### ISSUE THREAD

**Issue by lpandzic** [FasterXML/jackson-module-parameter-names#12]
Travis is simpler to manage and doesn't hibernate instances like Cloudbees.

**Comment by prb** [comment]
I'm in favor, although what we should do it run this across the whole suite of FasterXML projects, including Jackson and modules.

**Comment by lpandzic** [comment]
Can you enable the job on https://travis-ci.org/FasterXML/jackson-module-parameter-names?

**Comment by prb** [comment]
Done!  I also updated the build badge in `README.md`.

**Comment by lpandzic** [comment]
Nice, thanks!
