### ISSUE TITLE
README.md example does not work

### ISSUE THREAD

**Issue by tazle** [FasterXML/jackson-module-parameter-names#19]
The Person example in README.md does not work with jackson-module-parameter-names 2.5.3. ParameterNamesAnnotationInspector gets called to resolve the names of Person(String, String) parameters, but since the constructor doesn't have @JsonCreator annotation, they are discarded at _addCreatorParam of POJOPropertiesCollector.java (line 482).

If I add @JsonCreator on the constructor, the example works as expected.

**Comment by lpandzic** [comment]
Hello @tazle, this was an oversight on my part. I`ve updated README.md too early. It will work with jackson 2.6.0 when it is released and it should work with 2.6.0-rc1.
I'll submit a pull request which will update README.md to reflect this fact.
Thank you for your report.
