### ISSUE TITLE
Using Mode.PROPERTIES for ParameterNamesModule causes simple value constructors to fail

### ISSUE THREAD

**Issue by hjohn** [FasterXML/jackson-module-parameter-names#30]
This seems related to issue #5.

I have a simple class below SimpleConstructor that accepts a single String value.  When Jackson encounters this class with the ParameterNamesModule and Mode.PROPERTIES, it will fail to construct a simple instance of the class and instead throws this error:

```
Can not instantiate value of type [simple type, class SimpleConstructorTest$SimpleConstructor] from String value ('value'); no single-String constructor/factory method
```

There seems to be no way to annotate this type or constructor to indicate it is a simple value type.

I also don't really understand why it would be ambigious... a value looks like:

```
"<value>"
```

While an object (which it seems to expect) looks like:

```
 {"constructorParameterName": "<value>"}
```

Here is a test case reproducing the issue.  Make sure that code is compiled with the -parameters switch.

```
import static org.junit.Assert.assertEquals;

import java.util.List;

import org.junit.Test;

import com.fasterxml.jackson.annotation.JsonCreator.Mode;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.module.paramnames.ParameterNamesModule;

public class SimpleConstructorTest {

    private static final TypeReference<List<SimpleConstructor>> SIMPLE_CONSTRUCTOR_REF
            = new TypeReference<List<SimpleConstructor>>() {};

    @Test
    public void testSimpleConstructorWithParametersModuleModeProperties() throws Exception {
        final ObjectMapper mapper = new ObjectMapper();

        mapper.registerModule(new ParameterNamesModule(Mode.PROPERTIES));

        final List<SimpleConstructor> value = mapper.readValue("[\"value\"]", SIMPLE_CONSTRUCTOR_REF);
        // Above line fails with JsonMappingException
        assertEquals(1, value.size());
        assertEquals("value", value.get(0).getValue());
    }

    @Test
    public void testSimpleConstructorWithParametersModuleModeDefault() throws Exception {
        final ObjectMapper mapper = new ObjectMapper();

        mapper.registerModule(new ParameterNamesModule());

        final List<SimpleConstructor> value = mapper.readValue("[\"value\"]",SIMPLE_CONSTRUCTOR_REF);
        assertEquals(1, value.size());
        assertEquals("value", value.get(0).getValue());
    }



    public static final class SimpleConstructor {
        private final String value;

        public SimpleConstructor(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }
    }
}
```

**Comment by cowtowncoder** [comment]
What I don't understand here is why you set `Mode.PROPERTIES` -- that would explicit force assumption that data to come in MUST be in form of an Object with single property with name `value`.
So I would expect this to fail.

However: error message given should be different; it should not claim that there is no constructor (there is), but rather that it is unclear as to how to map JSON String into Object with properties.

**Comment by hjohn** [comment]
I was hoping ```Mode.PROPERTIES``` would allow:

   "value" --> Constructor(String value)
   {"a": "1", "b": 2} --> Constructor(String a, int b)

but not:

   {"a": "1", "b": 2} --> Constructor(String json)

If that's not the case then I'm not using the right mode.

You're right though that the error message is a bit confusing, especially since there is a constructor with a single string parameter :)

**Comment by cowtowncoder** [comment]
@hjohn Unfortunately, as things are, only one single constructor (or factory method) can be designated to be "the" creator, and this is why separation is needed. Ideally it would be possible to allow multiple constructors like you are doing.

If you need to support above-mentioned two cases, you can still do that, by using delegating approach with either type `JsonNode` or `java.lang.Object`: in former case, you'd get either `ObjectNode` (for JSON Object) or `StrginNode` (JSON String). If using nominal type of `Object`, you'd get `Map` (JSON Object) or `java.lang.String` (JSON String).
This is bit more code (constructor has to decide, or throw exception for unacceptable type), but does work.

I'll keep this open to see if and how error message could be improved, on short term. And perhaps file an RFE for trying to allow multiple constructor in future.

**Comment by cowtowncoder** [comment]
This module is moving to:

https://github.com/FasterXML/jackson-modules-java8

and I'll be closing this issue, as I don't think it may really be solved at least not with Jackson 2.x.
It may be possible that something could be done for 3.x, which will be started early next year.
