### ISSUE TITLE
ParameterNamesAnnotationIntrospector breaks @JsonProperty for enums

### ISSUE THREAD

**Issue by Raniz85** [FasterXML/jackson-module-parameter-names#36]
It's used as the primary annotation introspector in the `AnnotationIntrospectorPair` and as such it's `return enum.value()` will override the functionality introduced in [databind#677](https://github.com/FasterXML/jackson-databind/issues/677).

**Comment by cowtowncoder** [comment]
Could it be that #32 fixed this? (incuded in 2.7.3). Sounds similar, and there's a test.

Assuming it was the same thing; may be reopened with reproducible test case if there's another problem.
