### ISSUE TITLE
Module Causes "Simple Type Constructors" to Fail

### ISSUE THREAD

**Issue by alexwen** [FasterXML/jackson-module-parameter-names#5]
If I have a simple type constructor:

```
public static final class SimpleConstructor {
    private final String value;

    public SimpleConstructor(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }
}
```

And I add the module parameter names module, the class will no longer work as Jackson detects that the one parameter, "value" in the above example, has a name and thus it can no longer be constructor from just a string (and presumably any of the other simple types).

Here a JUnit test demonstrating the issue:

```
public class SimpleConstructorTest {

    private static final TypeReference<List<SimpleConstructor>> SIMPLE_CONSTRUCTOR_REF 
            = new TypeReference<List<SimpleConstructor>>() {};

    @Test
    public void testSimpleConstructorWithParametersModule() throws Exception {
        final ObjectMapper mapper = new ObjectMapper();

        mapper.registerModule(new ParameterNamesModule());

        final List<SimpleConstructor> value = mapper.readValue("[\"value\"]", SIMPLE_CONSTRUCTOR_REF);
        // Above line fails with JsonMappingException
        assertEquals(1, value.size());
        assertEquals("value", value.get(0).getValue());
    }

    @Test
    public void testSimpleConstructorWithoutParametersModule() throws Exception {
        final ObjectMapper mapper = new ObjectMapper();

        final List<SimpleConstructor> value = mapper.readValue("[\"value\"]",SIMPLE_CONSTRUCTOR_REF);
        assertEquals(1, value.size());
        assertEquals("value", value.get(0).getValue());
    }

    public static final class SimpleConstructor {
        private final String value;

        public SimpleConstructor(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }
    }
}
```

**Comment by luskwater** [comment]
I believe I'm encountering this same problem using Resteasy `3.0.10.Final` with the `resteasy-jackson2-provider`. I'm using **Jackson 2.5.1**.

### Symptom<a id="sec-1" name="sec-1"></a> ###

All tests run successfully in *Eclipse*. Running tests from *Maven* fails, whether done within *Eclipse* or from the command-line.  (Line breaks added to output below, marked by backslash.)

    testListAll(xxx.xxxxxx.xxx.xxxxxx.rest.PackagesTest)  Time elapsed: 0.248 sec  <<< FAILURE!
    java.lang.AssertionError: Exception encountered: com.fasterxml.jackson.databind.JsonMappingException: \
    Can not instantiate value of type java.util.HashMap from \
    String value ('de0ede87-26d3-4559-a18e-84326fd20eb6'); \
    no single-String constructor/factory method
     at [Source: ["de0ede87-26d3-4559-a18e-84326fd20eb6"]; line: 1, column: 2]
            at org.junit.Assert.fail(Assert.java:88)
            at xxx.xxxxxx.xxx.xxxxxx.rest.RESTJsonTest.extractJsonStuff(RESTJsonTest.java:213)
            at xxx.xxxxxx.xxx.xxxxxx.rest.PackagesTest.testListAll(PackagesTest.java:112)

The failing code is

    TypeReference<List<HashMap<String,String>>> ref =
        new TypeReference<List<HashMap<String,String>>>() {};
    List<HashMap<String,String>> extractedResults = extractJsonStuff(response, ref);

(It also failed with the original `Map<String,Object>` that I used.)

The JSON being parsed is

    [{"generatedTimestamp":"2015-02-20 06:54:21.000",
      "uuid":"de0ede87-26d3-4559-a18e-84326fd20eb6",
      "originalFileName":"RandomFilename.pkm",
      "generatedBy":"999999",
      "insertionTime":"2015-05-21 12:34:56.000",
      "name":"ThingName",
      "state":"QUEUED",
      "type":"FooBar",
      "version":"4.0.0-RELEASE",
      "description":"Token package"}]

### Diagnosis<a id="sec-2" name="sec-2"></a> ###

Not sure: the code snippet executes just fine in Eclipse, but not in Maven.

### Cure<a id="sec-3" name="sec-3"></a> ###

Sure would like one.

**Comment by cowtowncoder** [comment]
@luskwater I am not sure you are facing the same problem here; symptom does not sound like one issue talks about. Instead this looks like a mismatch between JSON String value, and expected Java Map value.

**Comment by hjohn** [comment]
I have the same problem as the original submitter, except that I also use Mode.PROPERTIES for the ParameterNamesModule (you can reproduce with the original test case submitted and including this mode).

My problem is that when I have a simple type that accepts a String (basically a "typed" wrapper for String) that I get an exception: com.fasterxml.jackson.databind.JsonMappingException: 

    Can not instantiate value of type [simple type, class SimpleConstructorTest$SimpleConstructor] from String value ('value'); no single-String constructor/factory method

There seems to be no way to annotate this type or constructor to indicate it is a simple value type.

I also don't really understand why it would be ambigious... a value looks like:

     "<value>"

While an Object would look like:

     {"constructorParameterName": "<value>"}

**Comment by lpandzic** [comment]
What is the name of the field in json and what is the name of the parameter name in constructor?
Can you provide a complete code example which fails?

**Comment by cowtowncoder** [comment]
@hjohn as @lpandzic suggested, a unit test would be needed. But also: please file a new issue for this (with ref to this one); it may be related to the original issue (or might not be), but it is much easier to track release notes and progress when issue life-cycle is clear. That is, re-opening an old issue makes it difficult to reason about version in which various problem has been fixed.

It will be easier to explain behavior with a reproducible test case.

**Comment by hjohn** [comment]
Opened #30
