### ISSUE TITLE
Absence and presence of @JsonCreator might have no affect

### ISSUE THREAD

**Issue by jaysonminard** [FasterXML/jackson-module-parameter-names#7]
See: https://github.com/FasterXML/jackson-module-paranamer/issues/11

see other comments there, it is related to all modules trying to do this.

**Comment by lpandzic** [comment]
This issue can be closed now after https://github.com/FasterXML/jackson-module-parameter-names/issues/13?

**Comment by cowtowncoder** [comment]
I think so. If anyone disagrees, please re-open with comment indicating why it is still relevant.
